#version 430 compatibility
#extension GL_ARB_compute_shader : enable
#extension GL_ARB_shader_storage_buffer_object : enable

layout( std140, binding=7 ) buffer Dist {
	float distances[];
};

layout( shared, binding=8 ) buffer Idx {
	uint indices[];
};

layout( local_size_x = 128,  local_size_y = 1, local_size_z = 1 ) in;

void main() {

	uint  gid = gl_GlobalInvocationID.x;
	distances[indices[gid]] = distances[indices[gid]] + 1;
}